# Generated by Django 2.1.1 on 2019-08-06 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_photo_hitcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='hitcount',
        ),
    ]
